### ISSUE TITLE
Zoom Crosshair not working

### ISSUE THREAD

**Issue by arkprocession** [AoiKagase/Amxx-CrosshairMenu#1]
Don't know if you forked this to maintain it but i shall give it a try.

When you zoom with a weapon, the crosshair goes back to default cz crosshair.

Is that fixable?

**Comment by AoiKagase** [comment]
I think it is theoretically possible, but i won't know until we try.
And I can't take much time right now, so my response(fix) will be delayed.

**Comment by arkprocession** [comment]
> I think it is theoretically possible, but i won't know until we try. And I can't take much time right now, so my response(fix) will be delayed.

I understand.

Will check on this from time to time to see if anything changes, thanks!

**Comment by AoiKagase** [comment]
Due to the specifications of this plugin, custom weapons cannot be supported.
It will only be AUG/SG552.

**Comment by arkprocession** [comment]
> Due to the specifications of this plugin, custom weapons cannot be supported. It will only be AUG/SG552.

That is just fine.

I do not use custom weapons.
