### ISSUE TITLE
Add Crosshair to Snipers

### ISSUE THREAD

**Issue by arkprocession** [AoiKagase/Amxx-CrosshairMenu#4]
Hello,

Could you please, Add the static Crosshair to AWP, Scout, and also Krieg 550 Commando and D3/AU-1 Semi-Auto Sniper Rifle
I mean when not aiming with RIGHT CLICK you can see the crosshair just like the other weapons.

**Comment by AoiKagase** [comment]
`crosshair_snipers` `1`
I thought the sniper was optional so I added a CVAR.

**Comment by arkprocession** [comment]
> `crosshair_snipers` `1` I thought the sniper was optional so I added a CVAR.

It seems to work for all snipers except AWP. Trying to look at the code to see if i can find anything that causes it

**Comment by arkprocession** [comment]
Crosshair for AWP works perfectly, thanks!
